services:
  - type: web
    name: cut-n-edge
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    staticPublishPath: ./static
    envVars:
      - key: SENDER_EMAIL
        sync: false
      - key: BUSINESS_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false